set(ARCH MOS CACHE STRING "")

if (NOT DEFINED LLVM_MOS)
  message(FATAL_ERROR "LLVM_MOS must be set to a llvm-mos SDK installation.")
endif()
file(TO_CMAKE_PATH "${LLVM_MOS}" llvm_mos_path)
set(LLVM_MOS ${llvm_mos_path} CACHE STRING "" FORCE)

if(WIN32)
  set(TEST_SUITE_HOST_CC "gcc" CACHE STRING "")
endif()
set(TEST_SUITE_RUN_UNDER ${LLVM_MOS}/bin/mos-sim CACHE STRING "")
set(TEST_SUITE_USER_MODE_EMULATION yes CACHE BOOL "")
set(TEST_SUITE_LLVM_SIZE "" CACHE STRING "")
set(CMAKE_STRIP "" CACHE STRING "")
set(CMAKE_TOOLCHAIN_FILE ${CMAKE_CURRENT_LIST_DIR}/util/llvm-mos-toolchain.cmake CACHE STRING "")
