set(ARCH MOS CACHE STRING "")

find_program(TEST_SUITE_RUN_UNDER mos-sim HINTS ${LLVM_MOS}/bin)

set(TEST_SUITE_USER_MODE_EMULATION yes CACHE BOOL "")
set(TEST_SUITE_LLVM_SIZE "" CACHE STRING "")
set(CMAKE_STRIP "" CACHE STRING "")
set(CMAKE_TOOLCHAIN_FILE ${CMAKE_CURRENT_LIST_DIR}/util/llvm-mos-toolchain.cmake CACHE STRING "")
